# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1917o48l9b-5zEUHqADPizWO-7HM8uxp4
"""

from pprint import pprint

class ModelConfig:

  def __init__(self,train_transform=None):
    super(ModelConfig, self).__init__()
    self.seed = 1
    self.batch_size_cuda = 128
    self.batch_size_cpu = 64	
    self.num_workers = 4
    self.epochs = 50
    self.dropout_value = 0.1
    self.train_transform = train_transform

  def print_config(self):
    print("Model Parameters:")
    pprint(vars(self), indent=2)
